baseurl = "http://localhost:1313/"
title = "britney-wang"
theme = "hugo-theme-console"
languageCode = "en-us"

[params]
  author = "Britney Wang"
  description = "Software engineer portfolio"

  # Cutting off the page title to two chars for mobile (console-demo -> co)
  titleCutting = true

  # Set the animation style -- https://animate.style/
  # To disable animations, please remove or comment animationStyle parameter
  animateStyle = "animated zoomIn fast" 

  [[params.navlinks]]
  name = "resume/"
  url = "resume/"

  [[params.navlinks]]
  name = "projects/"
  url = "projects/"
